var data = {
   "1996":{
      "countries":{
         "498":{
            "enfants":"10"
         },
         "642":{
            "enfants":"1"
         }
      },
      "sites":{
         "LA":"11"
      }
   },
   "1997":{
      "countries":{
         "120":{
            "enfants":"2"
         },
         "356":{
            "enfants":"1"
         },
         "450":{
            "enfants":"1"
         },
         "466":{
            "enfants":"1"
         },
         "498":{
            "enfants":"25"
         },
         "643":{
            "enfants":"1"
         },
         "760":{
            "enfants":"5"
         },
         "804":{
            "enfants":"7"
         },
         "818":{
            "enfants":"1"
         }
      },
      "sites":{
         "LA":"44"
      }
   },
   "1998":{
      "countries":{
         "12":{
            "enfants":"8"
         },
         "120":{
            "enfants":"2"
         },
         "192":{
            "enfants":"1"
         },
         "450":{
            "enfants":"1"
         },
         "466":{
            "enfants":"6"
         },
         "478":{
            "enfants":"2"
         },
         "498":{
            "enfants":"14"
         },
         "504":{
            "enfants":"1"
         },
         "642":{
            "enfants":"1"
         },
         "760":{
            "enfants":"7"
         },
         "804":{
            "enfants":"4"
         },
         "818":{
            "enfants":"5"
         },
         "854":{
            "enfants":"1"
         }
      },
      "sites":{
         "LA":"53"
      }
   },
   "1999":{
      "countries":{
         "12":{
            "enfants":"8"
         },
         "108":{
            "enfants":"1"
         },
         "120":{
            "enfants":"1"
         },
         "148":{
            "enfants":"1"
         },
         "174":{
            "enfants":"1"
         },
         "180":{
            "enfants":"1"
         },
         "324":{
            "enfants":"1"
         },
         "384":{
            "enfants":"2"
         },
         "418":{
            "enfants":"5"
         },
         "450":{
            "enfants":"6"
         },
         "466":{
            "enfants":"6"
         },
         "478":{
            "enfants":"1"
         },
         "498":{
            "enfants":"9"
         },
         "504":{
            "enfants":"3"
         },
         "704":{
            "enfants":"2"
         },
         "760":{
            "enfants":"7"
         },
         "818":{
            "enfants":"1"
         },
         "854":{
            "enfants":"1"
         }
      },
      "sites":{
         "NE":"12",
         "LA":"44"
      }
   },
   "2000":{
      "countries":{
         "12":{
            "enfants":"8"
         },
         "108":{
            "enfants":"1"
         },
         "120":{
            "enfants":"2"
         },
         "156":{
            "enfants":"1"
         },
         "178":{
            "enfants":"1"
         },
         "180":{
            "enfants":"1"
         },
         "324":{
            "enfants":"1"
         },
         "332":{
            "enfants":"2"
         },
         "384":{
            "enfants":"2"
         },
         "418":{
            "enfants":"9"
         },
         "422":{
            "enfants":"1"
         },
         "450":{
            "enfants":"5"
         },
         "466":{
            "enfants":"26"
         },
         "478":{
            "enfants":"2"
         },
         "498":{
            "enfants":"8"
         },
         "504":{
            "enfants":"6"
         },
         "686":{
            "enfants":"2"
         },
         "704":{
            "enfants":"6"
         },
         "760":{
            "enfants":"8"
         },
         "854":{
            "enfants":"1"
         }
      },
      "sites":{
         "NE":"88",
         "LA":"1"
      }
   },
   "2001":{
      "countries":{
         "12":{
            "enfants":"5"
         },
         "108":{
            "enfants":"4"
         },
         "116":{
            "enfants":"1"
         },
         "266":{
            "enfants":"1"
         },
         "384":{
            "enfants":"4"
         },
         "418":{
            "enfants":"15"
         },
         "450":{
            "enfants":"4"
         },
         "466":{
            "enfants":"18"
         },
         "478":{
            "enfants":"3"
         },
         "498":{
            "enfants":"15"
         },
         "504":{
            "enfants":"7"
         },
         "562":{
            "enfants":"1"
         },
         "586":{
            "enfants":"2"
         },
         "642":{
            "enfants":"1"
         },
         "686":{
            "enfants":"2"
         },
         "704":{
            "enfants":"11"
         },
         "760":{
            "enfants":"11"
         },
         "804":{
            "enfants":"1"
         },
         "-3":{
            "enfants":"1"
         }
      },
      "sites":{
         "NE":"103"
      }
   },
   "2002":{
      "countries":{
         "12":{
            "enfants":"16"
         },
         "108":{
            "enfants":"1"
         },
         "120":{
            "enfants":"4"
         },
         "156":{
            "enfants":"1"
         },
         "180":{
            "enfants":"3"
         },
         "262":{
            "enfants":"1"
         },
         "384":{
            "enfants":"1"
         },
         "417":{
            "enfants":"1"
         },
         "418":{
            "enfants":"13"
         },
         "450":{
            "enfants":"5"
         },
         "466":{
            "enfants":"16"
         },
         "478":{
            "enfants":"3"
         },
         "498":{
            "enfants":"18"
         },
         "504":{
            "enfants":"8"
         },
         "562":{
            "enfants":"2"
         },
         "686":{
            "enfants":"4"
         },
         "704":{
            "enfants":"5"
         },
         "760":{
            "enfants":"6"
         },
         "818":{
            "enfants":"4"
         },
         "854":{
            "enfants":"1"
         },
         "882":{
            "enfants":"1"
         },
         "887":{
            "enfants":"1"
         }
      },
      "sites":{
         "NE":"107",
         "SJ":"1"
      }
   },
   "2003":{
      "countries":{
         "12":{
            "enfants":"15"
         },
         "24":{
            "enfants":"18"
         },
         "120":{
            "enfants":"5"
         },
         "148":{
            "enfants":"1"
         },
         "178":{
            "enfants":"6"
         },
         "180":{
            "enfants":"7"
         },
         "204":{
            "enfants":"1"
         },
         "266":{
            "enfants":"5"
         },
         "332":{
            "enfants":"1"
         },
         "368":{
            "enfants":"3"
         },
         "384":{
            "enfants":"3"
         },
         "418":{
            "enfants":"15"
         },
         "450":{
            "enfants":"7"
         },
         "466":{
            "enfants":"17"
         },
         "478":{
            "enfants":"4"
         },
         "498":{
            "enfants":"10"
         },
         "504":{
            "enfants":"5"
         },
         "562":{
            "enfants":"2"
         },
         "646":{
            "enfants":"1"
         },
         "686":{
            "enfants":"6"
         },
         "760":{
            "enfants":"16"
         },
         "776":{
            "enfants":"2"
         },
         "818":{
            "enfants":"5"
         }
      },
      "sites":{
         "NE":"131",
         "MS":"1",
         "SJ":"2"
      }
   },
   "2004":{
      "countries":{
         "4":{
            "enfants":"1"
         },
         "12":{
            "enfants":"17"
         },
         "24":{
            "enfants":"11"
         },
         "108":{
            "enfants":"2"
         },
         "120":{
            "enfants":"5"
         },
         "140":{
            "enfants":"1"
         },
         "148":{
            "enfants":"1"
         },
         "156":{
            "enfants":"1"
         },
         "178":{
            "enfants":"8"
         },
         "180":{
            "enfants":"9"
         },
         "231":{
            "enfants":"1"
         },
         "332":{
            "enfants":"1"
         },
         "384":{
            "enfants":"1"
         },
         "417":{
            "enfants":"1"
         },
         "418":{
            "enfants":"25"
         },
         "450":{
            "enfants":"7"
         },
         "466":{
            "enfants":"22"
         },
         "478":{
            "enfants":"1"
         },
         "504":{
            "enfants":"14"
         },
         "562":{
            "enfants":"3"
         },
         "646":{
            "enfants":"1"
         },
         "686":{
            "enfants":"5"
         },
         "704":{
            "enfants":"3"
         },
         "760":{
            "enfants":"20"
         },
         "818":{
            "enfants":"3"
         },
         "854":{
            "enfants":"6"
         }
      },
      "sites":{
         "NE":"90",
         "AN":"2",
         "MS":"28",
         "NA":"1",
         "SJ":"14"
      }
   },
   "2005":{
      "countries":{
         "4":{
            "enfants":"1"
         },
         "12":{
            "enfants":"8"
         },
         "24":{
            "enfants":"7"
         },
         "108":{
            "enfants":"3"
         },
         "120":{
            "enfants":"7"
         },
         "178":{
            "enfants":"2"
         },
         "180":{
            "enfants":"2"
         },
         "266":{
            "enfants":"2"
         },
         "324":{
            "enfants":"1"
         },
         "368":{
            "enfants":"1"
         },
         "384":{
            "enfants":"2"
         },
         "418":{
            "enfants":"15"
         },
         "450":{
            "enfants":"4"
         },
         "466":{
            "enfants":"18"
         },
         "498":{
            "enfants":"1"
         },
         "504":{
            "enfants":"8"
         },
         "562":{
            "enfants":"6"
         },
         "686":{
            "enfants":"8"
         },
         "694":{
            "enfants":"1"
         },
         "760":{
            "enfants":"13"
         },
         "818":{
            "enfants":"3"
         },
         "854":{
            "enfants":"8"
         },
         "-3":{
            "enfants":"1"
         }
      },
      "sites":{
         "NE":"76",
         "BO":"3",
         "ML":"16",
         "MY":"1",
         "MS":"10",
         "SJ":"7"
      }
   },
   "2006":{
      "countries":{
         "12":{
            "enfants":"10"
         },
         "24":{
            "enfants":"5",
            "formations":"1"
         },
         "70":{
            "enfants":"1"
         },
         "108":{
            "enfants":"1",
            "formations":"1"
         },
         "120":{
            "enfants":"12",
            "formations":"2"
         },
         "140":{
            "enfants":"1"
         },
         "178":{
            "enfants":"4",
            "formations":"1"
         },
         "180":{
            "enfants":"1",
            "formations":"1"
         },
         "266":{
            "enfants":"1"
         },
         "324":{
            "enfants":"2"
         },
         "384":{
            "enfants":"1"
         },
         "417":{
            "enfants":"1"
         },
         "418":{
            "enfants":"11",
            "formations":"1"
         },
         "450":{
            "enfants":"3",
            "formations":"1"
         },
         "466":{
            "enfants":"11"
         },
         "478":{
            "enfants":"1",
            "formations":"1"
         },
         "496":{
            "enfants":"2"
         },
         "498":{
            "enfants":"1"
         },
         "504":{
            "enfants":"8"
         },
         "548":{
            "enfants":"2"
         },
         "562":{
            "enfants":"3",
            "formations":"1"
         },
         "646":{
            "enfants":"1"
         },
         "686":{
            "enfants":"7"
         },
         "704":{
            "enfants":"4"
         },
         "716":{
            "enfants":"1"
         },
         "760":{
            "enfants":"1"
         },
         "768":{
            "enfants":"2"
         },
         "818":{
            "enfants":"5"
         },
         "854":{
            "enfants":"5",
            "formations":"1"
         }
      },
      "sites":{
         "NE":"38",
         "BO":"9",
         "ML":"20",
         "GP":"8",
         "MS":"9",
         "SJ":"5"
      }
   },
   "2007":{
      "countries":{
         "12":{
            "enfants":"16"
         },
         "24":{
            "enfants":"6"
         },
         "108":{
            "enfants":"1"
         },
         "120":{
            "enfants":"4"
         },
         "132":{
            "enfants":"2",
            "formations":"1"
         },
         "140":{
            "enfants":"1",
            "formations":"1"
         },
         "178":{
            "enfants":"11"
         },
         "180":{
            "enfants":"1"
         },
         "214":{
            "formations":"1"
         },
         "266":{
            "enfants":"1",
            "formations":"1"
         },
         "324":{
            "enfants":"1",
            "formations":"1"
         },
         "332":{
            "formations":"1"
         },
         "368":{
            "enfants":"2"
         },
         "384":{
            "enfants":"9"
         },
         "418":{
            "enfants":"15",
            "formations":"1"
         },
         "450":{
            "enfants":"7",
            "formations":"2"
         },
         "466":{
            "enfants":"9",
            "formations":"1"
         },
         "496":{
            "enfants":"3"
         },
         "504":{
            "enfants":"5"
         },
         "562":{
            "enfants":"3"
         },
         "686":{
            "enfants":"5",
            "formations":"1"
         },
         "704":{
            "enfants":"4"
         },
         "760":{
            "enfants":"10"
         },
         "818":{
            "enfants":"2"
         },
         "854":{
            "enfants":"5"
         }
      },
      "sites":{
         "AN":"2",
         "BO":"10",
         "ML":"29",
         "GP":"29",
         "LY":"13",
         "MA":"3",
         "MS":"9",
         "SJ":"4",
         "TL":"8"
      }
   },
   "2008":{
      "countries":{
         "12":{
            "enfants":"8"
         },
         "24":{
            "enfants":"1"
         },
         "116":{
            "enfants":"1",
            "formations":"1"
         },
         "120":{
            "enfants":"15",
            "missions":"1"
         },
         "174":{
            "formations":"1"
         },
         "178":{
            "enfants":"12"
         },
         "180":{
            "enfants":"4"
         },
         "204":{
            "enfants":"1",
            "formations":"1"
         },
         "214":{
            "enfants":"3"
         },
         "266":{
            "enfants":"2"
         },
         "270":{
            "enfants":"1"
         },
         "324":{
            "enfants":"4",
            "formations":"1"
         },
         "332":{
            "enfants":"2"
         },
         "368":{
            "enfants":"9"
         },
         "384":{
            "enfants":"6"
         },
         "418":{
            "enfants":"11"
         },
         "450":{
            "enfants":"9"
         },
         "466":{
            "enfants":"49"
         },
         "496":{
            "enfants":"1"
         },
         "498":{
            "enfants":"1"
         },
         "504":{
            "enfants":"3",
            "formations":"2"
         },
         "562":{
            "enfants":"3",
            "formations":"1"
         },
         "686":{
            "enfants":"8",
            "formations":"1"
         },
         "704":{
            "formations":"2"
         },
         "760":{
            "enfants":"1"
         },
         "768":{
            "formations":"1"
         },
         "854":{
            "enfants":"4"
         },
         "860":{
            "enfants":"1"
         },
         "887":{
            "enfants":"1"
         }
      },
      "sites":{
         "NE":"1",
         "AN":"11",
         "BO":"14",
         "ML":"25",
         "GP":"42",
         "PE":"1",
         "LY":"13",
         "MA":"4",
         "NA":"11",
         "SJ":"11",
         "TL":"1",
         "TR":"9"
      }
   },
   "2009":{
      "countries":{
         "12":{
            "enfants":"3"
         },
         "108":{
            "enfants":"1"
         },
         "116":{
            "enfants":"2"
         },
         "120":{
            "enfants":"9",
            "formations":"1"
         },
         "140":{
            "enfants":"1"
         },
         "148":{
            "enfants":"1"
         },
         "174":{
            "enfants":"1"
         },
         "178":{
            "enfants":"10",
            "missions":"1"
         },
         "180":{
            "enfants":"1",
            "formations":"1"
         },
         "204":{
            "enfants":"2"
         },
         "214":{
            "enfants":"1"
         },
         "266":{
            "enfants":"1",
            "formations":"1"
         },
         "270":{
            "enfants":"1"
         },
         "324":{
            "enfants":"5"
         },
         "368":{
            "enfants":"13"
         },
         "384":{
            "enfants":"3",
            "formations":"1"
         },
         "418":{
            "enfants":"6"
         },
         "450":{
            "enfants":"12",
            "formations":"2"
         },
         "466":{
            "enfants":"22",
            "formations":"1"
         },
         "478":{
            "enfants":"1",
            "formations":"1"
         },
         "498":{
            "enfants":"1"
         },
         "504":{
            "enfants":"5"
         },
         "562":{
            "formations":"1"
         },
         "662":{
            "enfants":"1"
         },
         "686":{
            "enfants":"4",
            "missions":"1",
            "formations":"2"
         },
         "704":{
            "enfants":"1"
         },
         "760":{
            "enfants":"9",
            "missions":"1"
         },
         "818":{
            "enfants":"1"
         },
         "854":{
            "enfants":"3",
            "formations":"1"
         }
      },
      "sites":{
         "NE":"3",
         "AN":"2",
         "BO":"9",
         "ML":"5",
         "GP":"19",
         "LY":"8",
         "MY":"9",
         "NA":"9",
         "PS":"1",
         "SJ":"11",
         "TL":"3",
         "TR":"14"
      }
   },
   "2010":{
      "countries":{
         "12":{
            "enfants":"3"
         },
         "51":{
            "enfants":"1"
         },
         "108":{
            "enfants":"6",
            "formations":"1"
         },
         "116":{
            "enfants":"7"
         },
         "120":{
            "enfants":"11",
            "formations":"2"
         },
         "178":{
            "enfants":"15",
            "formations":"1"
         },
         "180":{
            "enfants":"5",
            "formations":"1"
         },
         "204":{
            "enfants":"2",
            "formations":"2"
         },
         "262":{
            "enfants":"4",
            "formations":"1"
         },
         "266":{
            "enfants":"1",
            "missions":"1",
            "formations":"1"
         },
         "324":{
            "enfants":"6"
         },
         "368":{
            "enfants":"6"
         },
         "384":{
            "enfants":"4"
         },
         "418":{
            "enfants":"9"
         },
         "450":{
            "enfants":"19"
         },
         "466":{
            "enfants":"22",
            "formations":"1"
         },
         "504":{
            "enfants":"5"
         },
         "562":{
            "enfants":"2",
            "missions":"1"
         },
         "686":{
            "enfants":"26"
         },
         "704":{
            "enfants":"1"
         },
         "760":{
            "enfants":"12",
            "missions":"1"
         },
         "768":{
            "formations":"1"
         },
         "854":{
            "enfants":"7",
            "missions":"1",
            "formations":"1"
         }
      },
      "sites":{
         "NE":"1",
         "AN":"5",
         "BO":"12",
         "ML":"17",
         "GP":"34",
         "LY":"12",
         "MA":"7",
         "MY":"46",
         "NA":"13",
         "SJ":"6",
         "TR":"17"
      }
   },
   "2011":{
      "countries":{
         "12":{
            "enfants":"6"
         },
         "108":{
            "enfants":"4"
         },
         "120":{
            "enfants":"9",
            "formations":"1"
         },
         "140":{
            "formations":"1"
         },
         "148":{
            "formations":"1"
         },
         "174":{
            "enfants":"2",
            "formations":"1"
         },
         "178":{
            "enfants":"4"
         },
         "180":{
            "enfants":"14",
            "missions":"1",
            "formations":"1"
         },
         "204":{
            "enfants":"4",
            "missions":"1"
         },
         "214":{
            "enfants":"1"
         },
         "262":{
            "enfants":"5",
            "missions":"1"
         },
         "266":{
            "enfants":"6",
            "formations":"1"
         },
         "324":{
            "enfants":"2"
         },
         "332":{
            "formations":"1"
         },
         "368":{
            "enfants":"10"
         },
         "384":{
            "enfants":"1"
         },
         "418":{
            "enfants":"3"
         },
         "450":{
            "enfants":"14",
            "missions":"1"
         },
         "466":{
            "enfants":"11"
         },
         "504":{
            "enfants":"6",
            "formations":"2"
         },
         "562":{
            "enfants":"10"
         },
         "686":{
            "enfants":"31",
            "formations":"1"
         },
         "729":{
            "enfants":"1"
         },
         "760":{
            "enfants":"15"
         },
         "768":{
            "formations":"1"
         },
         "854":{
            "enfants":"16"
         },
         "887":{
            "enfants":"1"
         }
      },
      "sites":{
         "AN":"3",
         "BO":"9",
         "ML":"30",
         "GP":"33",
         "LY":"10",
         "MA":"9",
         "MY":"55",
         "NA":"8",
         "SJ":"4",
         "TL":"2",
         "TR":"14"
      }
   },
   "2012":{
      "countries":{
         "12":{
            "enfants":"9",
            "formations":"1"
         },
         "108":{
            "enfants":"14",
            "missions":"1"
         },
         "120":{
            "enfants":"17"
         },
         "140":{
            "formations":"1"
         },
         "148":{
            "enfants":"1"
         },
         "174":{
            "enfants":"3"
         },
         "178":{
            "enfants":"5"
         },
         "180":{
            "enfants":"15",
            "formations":"1"
         },
         "204":{
            "enfants":"14",
            "formations":"1"
         },
         "262":{
            "enfants":"2"
         },
         "266":{
            "enfants":"4",
            "formations":"1"
         },
         "270":{
            "missions":"1"
         },
         "324":{
            "enfants":"5"
         },
         "332":{
            "enfants":"2"
         },
         "368":{
            "enfants":"1"
         },
         "384":{
            "enfants":"10"
         },
         "418":{
            "enfants":"8"
         },
         "450":{
            "enfants":"18",
            "formations":"1"
         },
         "466":{
            "enfants":"9"
         },
         "504":{
            "enfants":"5",
            "formations":"1"
         },
         "562":{
            "enfants":"5",
            "formations":"2"
         },
         "566":{
            "enfants":"2"
         },
         "686":{
            "enfants":"29",
            "formations":"1"
         },
         "760":{
            "enfants":"10"
         },
         "762":{
            "enfants":"1"
         },
         "768":{
            "enfants":"4",
            "missions":"1",
            "formations":"1"
         },
         "818":{
            "enfants":"1"
         },
         "854":{
            "enfants":"1",
            "formations":"1"
         }
      },
      "sites":{
         "AN":"4",
         "BO":"10",
         "ML":"40",
         "GP":"27",
         "LY":"7",
         "MA":"9",
         "MY":"69",
         "NA":"9",
         "SJ":"1",
         "ST":"3",
         "TL":"8",
         "TR":"8"
      }
   },
   "2013":{
      "countries":{

      },
      "sites":{

      }
   }
};

var countries = {
   "4":{
      "name":"Afghanistan",
      "total":"2"
   },
   "12":{
      "name":"Algérie",
      "total":"140"
   },
   "24":{
      "name":"Angola",
      "total":"48"
   },
   "51":{
      "name":"Arménie",
      "total":"1"
   },
   "70":{
      "name":"Bosnie",
      "total":"1"
   },
   "108":{
      "name":"Burundi",
      "total":"39"
   },
   "116":{
      "name":"Cambodge",
      "total":"11"
   },
   "120":{
      "name":"Cameroun",
      "total":"105"
   },
   "132":{
      "name":"Cap Vert",
      "total":"2"
   },
   "140":{
      "name":"Centre Afrique",
      "total":"4"
   },
   "148":{
      "name":"Tchad",
      "total":"5"
   },
   "156":{
      "name":"Chine",
      "total":"3"
   },
   "174":{
      "name":"Comores",
      "total":"7"
   },
   "178":{
      "name":"Congo",
      "total":"78"
   },
   "180":{
      "name":"RDC",
      "total":"64"
   },
   "192":{
      "name":"Cuba",
      "total":"1"
   },
   "204":{
      "name":"Benin",
      "total":"24"
   },
   "214":{
      "name":"Rép. Dominicaine",
      "total":"5"
   },
   "231":{
      "name":"Ethiopie",
      "total":"1"
   },
   "262":{
      "name":"Djibouti",
      "total":"12"
   },
   "266":{
      "name":"Gabon",
      "total":"24"
   },
   "270":{
      "name":"Gambie",
      "total":"2"
   },
   "324":{
      "name":"Guinée",
      "total":"28"
   },
   "332":{
      "name":"Haïti",
      "total":"8"
   },
   "356":{
      "name":"Inde",
      "total":"1"
   },
   "368":{
      "name":"Irak",
      "total":"45"
   },
   "384":{
      "name":"Côte d'Ivoire",
      "total":"49"
   },
   "417":{
      "name":"Kirghistan",
      "total":"3"
   },
   "418":{
      "name":"Laos",
      "total":"160"
   },
   "422":{
      "name":"Liban",
      "total":"1"
   },
   "450":{
      "name":"Madagascar",
      "total":"122"
   },
   "466":{
      "name":"Mali",
      "total":"263"
   },
   "478":{
      "name":"Mauritanie",
      "total":"18"
   },
   "496":{
      "name":"Mongolie",
      "total":"6"
   },
   "498":{
      "name":"Moldavie",
      "total":"113"
   },
   "504":{
      "name":"Maroc",
      "total":"89"
   },
   "548":{
      "name":"Vanuatu",
      "total":"2"
   },
   "562":{
      "name":"Niger",
      "total":"40"
   },
   "566":{
      "name":"Nigeria",
      "total":"2"
   },
   "586":{
      "name":"Pakistan",
      "total":"2"
   },
   "642":{
      "name":"Roumanie",
      "total":"3"
   },
   "643":{
      "name":"Russie",
      "total":"1"
   },
   "646":{
      "name":"Rwanda",
      "total":"3"
   },
   "662":{
      "name":"Sainte-Lucie",
      "total":"1"
   },
   "686":{
      "name":"Sénégal",
      "total":"137"
   },
   "694":{
      "name":"Sierra Léone",
      "total":"1"
   },
   "704":{
      "name":"Vietnam",
      "total":"37"
   },
   "716":{
      "name":"Zimbabwe",
      "total":"1"
   },
   "729":{
      "name":"Soudan",
      "total":"1"
   },
   "760":{
      "name":"Syrie",
      "total":"151"
   },
   "762":{
      "name":"Tadjikistan",
      "total":"1"
   },
   "768":{
      "name":"Togo",
      "total":"6"
   },
   "776":{
      "name":"Tonga",
      "total":"2"
   },
   "804":{
      "name":"Ukraine",
      "total":"12"
   },
   "818":{
      "name":"Egypte",
      "total":"31"
   },
   "854":{
      "name":"Burkina Faso",
      "total":"59"
   },
   "860":{
      "name":"Ouzbekistan",
      "total":"1"
   },
   "882":{
      "name":"Samoa",
      "total":"1"
   },
   "887":{
      "name":"Yemen",
      "total":"3"
   },
   "-3":{
      "name":"Kosovo",
      "total":"2"
   }
};

 var sites = {
   "NE":{
      "ville":"Paris",
      "hopital":"Hôpital Necker",
      "lat":"48.844871",
      "lng":"2.314746"
   },
   "AN":{
      "ville":"Angers",
      "hopital":"ANGERS",
      "lat":"47.4784190",
      "lng":"-0.563166"
   },
   "BO":{
      "ville":"Bordeaux",
      "hopital":"BORDEAUX",
      "lat":"44.8377890",
      "lng":"-0.579180"
   },
   "ML":{
      "ville":"Le Plessis-Robinson",
      "hopital":"Centre Chirurgical Marie Lannelongue",
      "lat":"48.784332",
      "lng":"2.273709"
   },
   "GP":{
      "ville":"Paris",
      "hopital":"Hôpital Européen Georges Pompidou",
      "lat":"48.83882",
      "lng":"2.273183"
   },
   "PE":{
      "ville":"Clamart",
      "hopital":"Hôpital d'instruction des armées Percy",
      "lat":"48.814438",
      "lng":"2.257004"
   },
   "LA":{
      "ville":"Paris",
      "hopital":"Hôpital Laennec",
      "lat":"48.849739",
      "lng":"2.321747"
   },
   "LY":{
      "ville":"Lyon",
      "hopital":"LYON",
      "lat":"45.7640430",
      "lng":"4.8356590"
   },
   "MA":{
      "ville":"Marseille",
      "hopital":"MARSEILLE",
      "lat":"43.2964820",
      "lng":"5.369780"
   },
   "MY":{
      "ville":"Massy",
      "hopital":"Hôpital Privé Jacques Cartier",
      "lat":"48.731427",
      "lng":"2.291873"
   },
   "MS":{
      "ville":"Paris",
      "hopital":"Institut Mutualiste Montsouris",
      "lat":"48.822618",
      "lng":"2.333028"
   },
   "NA":{
      "ville":"Nantes",
      "hopital":"NANTES",
      "lat":"47.217819",
      "lng":"-1.553793"
   },
   "PS":{
      "ville":"Paris",
      "hopital":"Hôpital de la Pitié-Salpétrière",
      "lat":"48.838382",
      "lng":"2.361031"
   },
   "SJ":{
      "ville":"Paris",
      "hopital":"Hôpital Saint-Joseph",
      "lat":"48.830254",
      "lng":"2.311152"
   },
   "ST":{
      "ville":"Strasbourg",
      "hopital":"STRASBOURG",
      "lat":"48.5831480",
      "lng":"7.7478820"
   },
   "TL":{
      "ville":"Toulouse",
      "hopital":"TOULOUSE",
      "lat":"43.6046520",
      "lng":"1.4442090"
   },
   "TR":{
      "ville":"Tours",
      "hopital":"TOURS",
      "lat":"47.3941440",
      "lng":"0.684840"
   }
};